name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildPlatformService:
    name: Build PlatformService

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./PlatformService
      run: dotnet restore
    - name: Build
      working-directory: ./PlatformService
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./PlatformService
      run: dotnet test --no-build --verbosity normal
  
  buildCommandsService:
    name: Build CommandsService

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./CommandsService
      run: dotnet restore
    - name: Build
      working-directory: ./CommandsService
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./CommandsService
      run: dotnet test --no-build --verbosity normal
