name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  buildPlatformService:
    name: Build PlatformService
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./PlatformService
      run: docker build . --file Dockerfile --tag grenkin/platformservice
  
  buildCommandsService:
    name: Build CommandsService
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./CommandsService
      run: docker build . --file Dockerfile --tag grenkin/commandservice